server:
  port: 8080

spring:
  application:
    name: finledger-backend
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    oauth2:
      client:
        registration:
          replit:
            client-id: ${REPL_ID}
            client-secret: ${CLIENT_SECRET:}
            scope: openid,email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          replit:
            issuer-uri: ${ISSUER_URL:https://replit.com/oidc}
            authorization-uri: https://replit.com/oidc/auth
            token-uri: https://replit.com/oidc/token
            user-info-uri: https://replit.com/oidc/userinfo
            jwk-set-uri: https://replit.com/oidc/jwks

logging:
  level:
    com.finledger.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG